# This is a basic workflow to help you get started with Actions

name: deploy-sa
on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*"]
  workflow_dispatch:
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter on bicep file
        run: az bicep linter build --file storage.bicep
