# This is a basic workflow to help you get started with Actions

name: deploy-sa
on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*"]
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

env:
  AZ_RG_NAME: RG11
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{secrets.AZ_CLIENT_ID}}
          subscription-id: ${{secrets.AZ_SUB_ID}}
          tenant-id: ${{secrets.AZ_TENANT_ID}}
      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript:
            az group create --name ${{env.AZ_RG_NAME}} --location WestEurope
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.AZ_RG_NAME}}
          template: ./storage.bicep
      - name: Deploy Bicep file for container
        uses: azure/arm-deploy@v1
        id: deploy-sa-container
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.AZ_RG_NAME}}
          template: ./blobcontainer.bicep
          parameters: mysaname=${{steps.deploy-sa.outputs.mysaname}}
