# This is a basic workflow to help you get started with Actions

name: deploy-sa
on:
  push:
    branches: [ "main" ]
    paths-ignore: [".github/workflows/*"]
  workflow_dispatch:
  
env:
  AZ_RG_NAME: RG10
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run linter on bicep file
        run:  az bicep build --file storage.bicep

  deploy:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - uses: actions/checkout@v3
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{secrets.AZ_CREDS}}
      - name: Create RG
        uses: azure/cli@v1
        with:
          inlineScript:
            az group create --name ${{env.AZ_RG_NAME}} --location WestEurope
      - name: Deploy Bicep file
        uses: azure/arm-deploy@v1
        id: deploy-sa
        with:
          deploymentName: ${{github.run_number}}
          resourceGroupName: ${{env.AZ_RG_NAME}}
          template: ./storage.bicep
